### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#24]
I created a sample project and tried the project.
```python3 ya2ro.py -i test_files/test_dg.yaml -o out/```
Response:
```
Traceback (most recent call last):
  File "/home/dgarijo/Documents/GitHub/EELISA-research-object/ya2ro.py", line 119, in <module>
    main()
  File "/home/dgarijo/Documents/GitHub/EELISA-research-object/ya2ro.py", line 47, in main
    import properties
ModuleNotFoundError: No module named 'properties'
```

I think the installation instructions are incomplete. Somef is not installed in my environment either, which will likely make fail the application

**Comment by PavelAntonia** [comment]
I've added SOMEF to the requirments.txt. I've run some tests in a fresh virtualenv and now it should work.
