### ISSUE TITLE
Error when fields from a person (e.g. institution) is not available from ORCID

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#30]
Example, with ORCID: https://orcid.org/0000-0001-7588-6094 I got an error

Error:
```
ERROR: Unable to retrieve the affiliations, check if https://orcid.org/0000-0001-7588-6094 is up.
Traceback (most recent call last):
  File "/home/dgarijo/Documents/GitHub/ya2ro/ya2ro.py", line 119, in <module>
    main()
  File "/home/dgarijo/Documents/GitHub/ya2ro/ya2ro.py", line 58, in main
    process_yaml(args.input)
  File "/home/dgarijo/Documents/GitHub/ya2ro/ya2ro.py", line 93, in process_yaml
    data = data_wrapper.load_yaml(yaml)
  File "/home/dgarijo/Documents/GitHub/ya2ro/data_wrapper.py", line 174, in load_yaml
    data = init_paper(p.input_to_vocab, data)
  File "/home/dgarijo/Documents/GitHub/ya2ro/data_wrapper.py", line 273, in init_paper
    populate_authors(paper, input_to_vocab, data)
  File "/home/dgarijo/Documents/GitHub/ya2ro/data_wrapper.py", line 509, in populate_authors
    object.authors[i].position = ", ".join(orcid.get_affiliation())
TypeError: can only join an iterable
```

**Comment by dgarijo** [comment]
I would like a test for this (see [this](https://realpython.com/python-testing/) to get started)
